### ISSUE TITLE
Store setup failed / take 2

### ISSUE THREAD

**Issue by kghbln** [rdfio/RDFIO#48]
**Setup**
- MediaWiki | 1.29.0 (a112e4f)20:23, 13 July 2017
- PHP | 5.6.30-0+deb8u1 (apache2handler)
- MariaDB | 10.0.32-MariaDB-1~jessie
- Semantic MediaWiki | 3.0.0-alpha (cea582e) 14:59, 7 August 2017
- RDFIO | v2.4.0 (6b69cb4) 23:41, 9 August 2017

**Issue***
There is still something in the water. I get
```
mysqli_connect(): Headers and client library minor version mismatch. Headers:50553 Library:100032 in /../w/vendor/semsol/arc2/store/ARC2_Store.php on line 51
```
This is probably an ARC2 issue.

However when trying to setup the RDFIO store via "RDFIOAdmin":
```
Error setting up store: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0210020150926 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE ut' at line 1 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0210020150926' at line 1 Could not create "triple" table (No database selected). in ARC2_StoreTableManager
```

**Comment by samuell** [comment]
Oh, thanks so much for reporting, @kghbln ! Hadn't dared to try with SMW 3 yet, but it is sure high time for that now! :)

**Comment by kghbln** [comment]
I believe there should not be that much of a difference, at least when it comes to database schema stuff.

**Comment by samuell** [comment]
Yeah, I was also suspecting it might be something with MariaDB and UTF8 ... as UTF8 issues have been abundant with MySQL in the past ...

**Comment by kghbln** [comment]
I have configured the database server to strictly run utf8:

```
Server characterset:	utf8
Db     characterset:	utf8
Client characterset:	utf8
Conn.  characterset:	utf8
```

**Comment by samuell** [comment]
@kghbln How do you go about installing SMW 3.0-alpha? Just git, or is there some way using composer? (Sorry, still kinda new to composer)

**Comment by kghbln** [comment]
> How do you go about installing SMW 3.0-alpha? Just git, or is there some way using composer? (Sorry, still kinda new to composer)

[INSTALL :)](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/INSTALL.md#installation-of-development-versions-and-release-candidates)

**Comment by samuell** [comment]
Ugh :blush:

**Comment by samuell** [comment]
Ok, with 3.0-alpa, I now get, on most RDFIO Special Pages:

A database query error has occurred. This may indicate a bug in the software.[62e20beab05666f7b3f67252] 2017-08-10 12:24:52: Fatal exception of type "Wikimedia\Rdbms\DBQueryError"

**Comment by kghbln** [comment]
> Ok, with 3.0-alpa, I now get, on most RDFIO Special Pages:

Ouch.

**Comment by samuell** [comment]
So, perhaps a confirmation then :) Hoping to get more details out of it ... did you do something special apart from `$wgShowExceptionDetails = true;` that doesn't seem to be enough here, to see the detailed error message?

**Comment by kghbln** [comment]
What about also using `$wgShowSQLErrors = true;` and `$wgShowDBErrorBacktrace = true;`?

**Comment by samuell** [comment]
Sorry, I feel I'm getting lazy, or too long since I did this :worried: ... thanks anyway!

```log
[12b39420dd18fd8b57956281] /w/index.php/Special:RDFIOAdmin Wikimedia\Rdbms\DBQueryError from line 1075 of /vagrant/w/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: SELECT smw_id,smw_sortkey,smw_sort FROM `smw_object_ids` WHERE smw_title = 'RDFIO_Import_Type' AND smw_namespace = '102' AND smw_iw = '' AND smw_subobject = '' LIMIT 1 
Function: SMWSql3SmwIds::getDatabaseIdAndSort
Error: 1054 Unknown column 'smw_sort' in 'field list' ()
Backtrace:

#0 /vagrant/w/includes/libs/rdbms/database/Database.php(933): Wikimedia\Rdbms\Database->reportQueryError(string, integer, string, string, boolean)
#1 /vagrant/w/includes/libs/rdbms/database/Database.php(1269): Wikimedia\Rdbms\Database->query(string, string)
#2 /vagrant/w/includes/libs/rdbms/database/Database.php(1337): Wikimedia\Rdbms\Database->select(string, array, array, string, array, array)
#3 /vagrant/w/extensions/SemanticMediaWiki/src/MediaWiki/Database.php(329): Wikimedia\Rdbms\Database->selectRow(string, array, array, string, array, array)
#4 /vagrant/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3SmwIds.php(385): SMW\MediaWiki\Database->selectRow(string, array, array, string)
#5 /vagrant/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3SmwIds.php(292): SMWSql3SmwIds->getDatabaseIdAndSort(string, integer, string, string, string, boolean, boolean)
#6 /vagrant/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_Sql3SmwIds.php(563): SMWSql3SmwIds->getSMWPageIDandSort(string, integer, string, string, string, boolean, boolean)
#7 /vagrant/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php(222): SMWSql3SmwIds->getSMWPageID(string, integer, string, string, boolean)
#8 /vagrant/w/extensions/SemanticMediaWiki/src/SQLStore/EntityStore/DirectEntityLookup.php(64): SMWSQLStore3Readers->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#9 /vagrant/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(213): SMW\SQLStore\EntityStore\DirectEntityLookup->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty, NULL)
#10 /vagrant/w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(154): SMWSQLStore3->getPropertyValues(SMW\DIWikiPage, SMW\DIProperty)
#11 /vagrant/w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(309): SMW\Store->getRedirectTarget(SMW\DIProperty)
#12 /vagrant/w/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Property.php(215): SMW\DIProperty->getRedirectTarget()
#13 /vagrant/w/extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php(192): SMWPropertyValue->parseUserValue(string)
#14 /vagrant/w/extensions/SemanticMediaWiki/src/DataValueFactory.php(147): SMWDataValue->setUserValue(string, boolean)
#15 /vagrant/w/extensions/SemanticMediaWiki/src/DataValueFactory.php(293): SMW\DataValueFactory->newDataValueByType(string, string, boolean, NULL, NULL)
#16 /vagrant/w/extensions/SemanticMediaWiki/includes/datavalues/SMW_DV_Property.php(115): SMW\DataValueFactory->newPropertyValueByLabel(string)
#17 /vagrant/w/extensions/SemanticMediaWiki/src/Query/PrintRequest/Deserializer.php(73): SMWPropertyValue::makeUserProperty(string)
#18 /vagrant/w/extensions/SemanticMediaWiki/src/Query/PrintRequest.php(306): SMW\Query\PrintRequest\Deserializer::deserialize(string, boolean)
#19 /vagrant/w/extensions/SemanticMediaWiki/src/Query/PrintRequestFactory.php(50): SMW\Query\PrintRequest::newFromText(string, boolean)
#20 /vagrant/w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(278): SMW\Query\PrintRequestFactory->newPrintRequestFromText(string, boolean)
#21 /vagrant/w/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php(333): SMWQueryProcessor::getComponentsFromFunctionParams(array, boolean)
#22 /vagrant/w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(248): SMWQueryProcessor::getQueryAndParamsFromFunctionParams(array, integer, integer, boolean, NULL)
#23 /vagrant/w/extensions/SemanticMediaWiki/src/ParserFunctions/AskParserFunction.php(166): SMW\ParserFunctions\AskParserFunction->doFetchResultsFromFunctionParameters(array, array)
#24 /vagrant/w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(307): SMW\ParserFunctions\AskParserFunction->parse(array)
#25 /vagrant/w/includes/parser/Parser.php(3408): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string, string, string)
#26 /vagrant/w/includes/parser/Parser.php(3128): Parser->callParserFunction(PPFrame_DOM, string, array)
#27 /vagrant/w/includes/parser/Preprocessor_DOM.php(1199): Parser->braceSubstitution(array, PPFrame_DOM)
#28 /vagrant/w/includes/parser/Parser.php(2942): PPFrame_DOM->expand(DOMElement, integer)
#29 /vagrant/w/includes/parser/Parser.php(1297): Parser->replaceVariables(string)
#30 /vagrant/w/includes/parser/Parser.php(451): Parser->internalParse(string)
#31 /vagrant/w/includes/OutputPage.php(1768): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#32 /vagrant/w/includes/OutputPage.php(1711): OutputPage->addWikiTextTitle(string, Title, boolean, boolean, boolean)
#33 /vagrant/w/extensions/Rdfio/specials/SpecialRDFIOAdmin.php(61): OutputPage->addWikiText(string)
#34 /vagrant/w/includes/specialpage/SpecialPage.php(522): RDFIOAdmin->execute()
#35 /vagrant/w/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(NULL)
#36 /vagrant/w/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#37 /vagrant/w/includes/MediaWiki.php(862): MediaWiki->performRequest()
#38 /vagrant/w/includes/MediaWiki.php(523): MediaWiki->main()
#39 /vagrant/w/index.php(43): MediaWiki->run()
#40 {main}
```

**Comment by samuell** [comment]
Ok, it works for me, with:

OS | Ubuntu 16.04.2 LTS
PHP | 7.0.18-0ubuntu0.16.04.1 (fpm-fcgi)
DB | MySQL 5.7.19-0ubuntu0.16.04.1
MediaWiki | 1.29.0
SMW | 3.0.0-alpha (e6137dd)
RDFIO | v2.4.0 (5a5fc01)

**Comment by kghbln** [comment]
I just successfully installed on smw.o:

- OS | Ubuntu 16.04.2 LTS
- MediaWiki | 1.27.3 (2fd9800)06:05, 7 July 2017
- PHP | 7.0.18-0ubuntu0.16.04.1 (apache2handler)
- MySQL | 5.7.19-0ubuntu0.16.04.1
- Semantic MediaWiki | 2.5.4 (9d8fac2) 14:13, 7 August 2017

So it is a MariaDB thing.

**Comment by samuell** [comment]
Ok, good to know! I have to learn a little MariaDB then, to figure this out :)

**Comment by kghbln** [comment]
> Ok, good to know! I have to learn a little MariaDB then, to figure this out :)

This will be awesome!

**Comment by samuell** [comment]
smw.o ... that's both cool, and scary - Hope any security flaws are found by friendly people then :D

**Comment by samuell** [comment]
At least I get:

![sparql endpoint - semantic-mediawiki org - chromium_321](https://user-images.githubusercontent.com/125003/29171258-339c9d04-7ddc-11e7-9e63-b86ca7f70c0f.png)

![rdf import - semantic-mediawiki org - chromium_322](https://user-images.githubusercontent.com/125003/29171260-3619b5f8-7ddc-11e7-9d00-b33dcebfe4c8.png)

:)

**Comment by kghbln** [comment]
I guess these pics should go to the other report? ;)

**Comment by samuell** [comment]
Yes, just saw it now

**Comment by kghbln** [comment]
> Ok, good to know! I have to learn a little MariaDB then, to figure this out :)

I just comes to my mind that Debian 9 which got released in June switched to MariaDB as the standard MySQL database system. So this will become more and more important in the future.

**Comment by kghbln** [comment]
> Yes, just saw it now

You could still move the pics over and delete the posts here.

**Comment by mwjames** [comment]
> @kghbln How do you go about installing SMW 3.0-alpha?

Yes, right now that shouldn't be any different to 2.5 since I haven't really started to dump all the deprecated classes/methods that have been accumulated of the years but things will change and ultimate break but as long as you test against master you can detect those fairly early.

PS: See the `DataValueFactory` or `DIProperty` class for example.
