### ISSUE TITLE
Rebuilding SMW data throws ARC2 errors

### ISSUE THREAD

**Issue by samuell** [rdfio/RDFIO#62]
```
$ php extensions/SemanticMediaWiki/maintenance/rebuildData.php 

Long-running scripts may cause memory leaks, if a deteriorating
rebuild process is detected (after many pages, typically more
than 10000), please abort with CTRL-C and resume this script
at the last processed ID using the parameter -s. Continue this
until all pages have been refreshed.

The progress displayed is an estimation and is self-adjusting 
during the maintenance process.

Running for storage: SMWARC2Store

Removing outdated entities and query links ...
   ... checking outdated entities ...
   ... done.
   ... checking invalid query links ...
   ... done.

Rebuilding property pages ...
   ... selecting 10 pages ...
   ... updating                                    100% (10/10)
   ... done.

Rebuilding semantic data ...
   ... selecting 1 to 521 IDs ...
   ... updating                                      0% (8/521)RDFIOARC2StoreException from line 132 of /var/www/html/w/extensions/Rdfio/stores/SMW_ARC2Store.php: Construct Template not found in ARC2_SPARQLPlusParser
#0 /var/www/html/w/extensions/Rdfio/stores/SMW_ARC2Store.php(90): SMWARC2Store->executeArc2Query('INSERT INTO <ht...')
#1 /var/www/html/w/extensions/SemanticMediaWiki/src/DataUpdater.php(403): SMWARC2Store->updateData(Object(SMW\SemanticData))
#2 /var/www/html/w/extensions/SemanticMediaWiki/src/DataUpdater.php(289): SMW\DataUpdater->updateData()
#3 /var/www/html/w/extensions/SemanticMediaWiki/src/DataUpdater.php(193): SMW\DataUpdater->runUpdate()
#4 /var/www/html/w/extensions/SemanticMediaWiki/src/ParserData.php(453): SMW\DataUpdater->doUpdate()
#5 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(296): SMW\ParserData->updateStore()
#6 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(216): SMW\MediaWiki\Jobs\UpdateJob->updateStore(Object(SMW\ParserData))
#7 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#8 /var/www/html/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#9 /var/www/html/w/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(237): SMW\MediaWiki\Jobs\UpdateJob->run()
#10 /var/www/html/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(423): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(9)
#11 /var/www/html/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(349): SMW\Maintenance\DataRebuilder->do_update(9)
#12 /var/www/html/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(200): SMW\Maintenance\DataRebuilder->rebuild_all()
#13 /var/www/html/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(202): SMW\Maintenance\DataRebuilder->rebuild()
#14 /var/www/html/w/maintenance/doMaintenance.php(99): SMW\Maintenance\RebuildData->execute()
#15 /var/www/html/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(261): require_once('/var/www/html/w...')
#16 {main}
```

**Comment by samuell** [comment]
This was fixed in a612852184b05cf12f3c8ee0f3e6c215f0b551aa
